Areas/Product/Controllers/ViewProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using App.Models;
using AppMvc.Areas.Product.Models;
using AppMvc.models;
using AppMvc.Models.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace AppMvc.Net.Areas.Product.Controllers
{
    [Area("Product")]
    public class ViewProductController : Controller
    {
        private readonly ILogger<ViewProductController> _logger;
        private readonly AppDbContext _context;

        private readonly CartService _cartService;

        public ViewProductController(ILogger<ViewProductController> logger, AppDbContext context, CartService cartService)
        {
            _logger = logger;
            _context = context;
            _cartService = cartService;
        }

        // /post/
        // /post/{categoryslug?}
        [Route("/product/{categoryslug?}")]
        public IActionResult Index(string categoryslug, [FromQuery(Name = "p")]int currentPage, int pagesize)
        {
            var categories = GetCategories();

            ViewBag.categories = categories;
            ViewBag.categoryslug = categoryslug;

            CategoryProduct category = null;

            if (!string.IsNullOrEmpty(categoryslug))    
            {
                category = _context.CategoryProducts.Where(c => c.Slug == categoryslug)
                                    .Include(c => c.CategoryChildren)
                                    .FirstOrDefault();

                if (category == null)
                {
                    return NotFound("Không thấy category");
                }                    
            }

            var products = _context.Products
                                .Include(p => p.Author)
                                .Include(p => p.Photos)
                                .Include(p => p.ProductCategoryProducts)
                                .ThenInclude(p => p.Category)
                                .AsQueryable();

            products = products.OrderByDescending(p => p.DateUpdated);

            if (category != null)
            {
                var ids = new List<int>();
                category.ChildCategoryIDs(null, ids);
                ids.Add(category.Id);


                products = products.Where(p => p.ProductCategoryProducts.Where(pc => ids.Contains(pc.CategoryID)).Any());


            }

            int totalProducts = products.Count();  
            if (pagesize <=0) pagesize = 6;
            int countPages = (int)Math.Ceiling((double)totalProducts / pagesize);
 
            if (currentPage > countPages) currentPage = countPages;     
            if (currentPage < 1) currentPage = 1; 

            var pagingModel = new PagingModel()
            {
                countpages = countPages,
                currentpage = currentPage,
                generateUrl = (pageNumber) => Url.Action("Index", new {
                    p =  pageNumber,
                    pagesize = pagesize
                })
            };

            var productsInPage = products.Skip((currentPage - 1) * pagesize)
                             .Take(pagesize);   


            ViewBag.pagingModel = pagingModel;
            ViewBag.totalPosts = totalProducts; 


                 
            ViewBag.category = category;
            return View(productsInPage.ToList());
        }

        [Route("/product/{productslug}.html")]
        public IActionResult Detail(string productslug)
        {
            var categories = GetCategories();
            ViewBag.categories = categories;

            var product = _context.Products.Where(p => p.Slug == productslug)
                               .Include(p => p.Author)
                               .Include(p => p.Photos)
                               .Include(p => p.ProductCategoryProducts)
                               .ThenInclude(pc => pc.Category)
                               .FirstOrDefault();

            if (product == null)
            {
                return NotFound("Không thấy bài viết");
            }            

            CategoryProduct category = product.ProductCategoryProducts.FirstOrDefault()?.Category;
            ViewBag.category = category;

            var otherProducts = _context.Products.Where(p => p.ProductCategoryProducts.Any(c => c.Category.Id == category.Id))
                                            .Where(p => p.ProductID != product.ProductID)
                                            .OrderByDescending(p => p.DateUpdated)
                                            .Take(5);
            ViewBag.otherProducts = otherProducts;                                

            return View(product);
        }

        private List<CategoryProduct> GetCategories()
        {
            var categories = _context.CategoryProducts
                            .Include(c => c.CategoryChildren)
                            .AsEnumerable()
                            .Where(c => c.ParentCategory == null)
                            .ToList();
            return categories;                
        }


        /// Thêm sản phẩm vào cart
        [Route ("addcart/{productid:int}", Name = "addcart")]
        public IActionResult AddToCart ([FromRoute] int productid) {

            var product = _context.Products
                .Where (p => p.ProductID == productid)
                .FirstOrDefault ();
            if (product == null)
                return NotFound ("Không có sản phẩm");

            // Xử lý đưa vào Cart ...
            var cart = _cartService.GetCartItems();
            var cartitem = cart.Find (p => p.product.ProductID == productid);
            if (cartitem != null) {
                // Đã tồn tại, tăng thêm 1
                cartitem.quantity++;
            } else {
                //  Thêm mới
                cart.Add (new CartItem () { quantity = 1, product = product });
            }

            // Lưu cart vào Session
            _cartService.SaveCartSession (cart);
            // Chuyển đến trang hiện thị Cart
            return RedirectToAction (nameof (Cart));
        }
        // Hiện thị giỏ hàng
        [Route ("/cart", Name = "cart")]
        public IActionResult Cart () 
        {
            return View (_cartService.GetCartItems());
        }
        
        /// xóa item trong cart
        [Route ("/removecart/{productid:int}", Name = "removecart")]
        public IActionResult RemoveCart ([FromRoute] int productid) {
            var cart = _cartService.GetCartItems ();
            var cartitem = cart.Find (p => p.product.ProductID == productid);
            if (cartitem != null) {
                // Đã tồn tại, tăng thêm 1
                cart.Remove(cartitem);
            }

            _cartService.SaveCartSession (cart);
            return RedirectToAction (nameof (Cart));
        }

        /// Cập nhật
        [Route ("/updatecart", Name = "updatecart")]
        [HttpPost]
        public IActionResult UpdateCart ([FromForm] int productid, [FromForm] int quantity) {
            // Cập nhật Cart thay đổi số lượng quantity ...
            var cart = _cartService.GetCartItems ();
            var cartitem = cart.Find (p => p.product.ProductID == productid);
            if (cartitem != null) {
                // Đã tồn tại, tăng thêm 1
                cartitem.quantity = quantity;
            }
            _cartService.SaveCartSession (cart);
            // Trả về mã thành công (không có nội dung gì - chỉ để Ajax gọi)
            return Ok();
        }

        [Route ("/checkout")]
        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartItems ();

            // ....
            _cartService.ClearCart();

            return Content("Da gui don hang");

        }

    }
}

Areas/Product/Views/ViewProduct/Cart.cshtml
@model List<AppMvc.Areas.Product.Models.CartItem>
@{
    Layout="_Layout";
}
<h2>GIỎ HÀNG</h2>

@if (Model.Count > 0) {
  decimal total = 0;
  int stt = 1;
  
  <table class="table">
    <tr>
      <th>#</th>
      <th>Sản phẩm</th>
      <th>Giá</th>
      <th>Số lượng</th>
      <th>Thành tiền</th>
      <th></th>
    </tr>
    @foreach (var cartitem in Model)
    {
        var thanhtien = cartitem.quantity * cartitem.product.Price;
        total += thanhtien;

        <tr>
           <td>@(stt++)</td>
           <td>@cartitem.product.Title</td>
           <td>@(cartitem.product.Price.ToString("n0"))</td>
           <td><input asp-for="@cartitem.quantity" id="@($"quantity-{cartitem.product.ProductID}")"/></td>
           <td>@(thanhtien.ToString("n0"))</td>
           <td>
              <button class="btn btn-success updatecartitem" 
                    data-productid="@cartitem.product.ProductID">Cập nhật</button>
              <a asp-route="removecart" asp-route-productid="@cartitem.product.ProductID"
                class="btn btn-danger">Xóa</a>
           </td>
        </tr>
    }
      <tr>
          <td colspan="4" class="text-right">Tổng tiền</td>
          <td>@(total.ToString("n0"))</td>
          <td></td>
      </tr>
  </table>

  <a asp-controller="ViewProduct" asp-action="Checkout" class="btn btn-success">Gửi đơn hàng</a>

      @section Scripts {
        <script>
          $(document).ready(function () {
              $(".updatecartitem").click(function (event) {
                  event.preventDefault();
                  var productid = $(this).attr("data-productid");
                  var quantity = $("#quantity-" + productid).val();
                  $.ajax({
                      type: "POST",
                      url:"@Url.RouteUrl("updatecart")",
                      data: {
                          productid: productid,
                          quantity:quantity
                      },
                      success: function (result) {
                          window.location.href = "@Url.RouteUrl("cart")";
                      }
                  });
              });
          });
        </script>
      }

}
else {
  <p class="alert alert-danger">Giỏ hàng trống</p>
}

Areas/Product/Views/ViewProduct/Detail.cshtml
@model ProductModel
@using AppMvc.Components

@{ 
    List<CategoryProduct> categories = ViewBag.categories as List<CategoryProduct>;
    CategoryProduct category = ViewBag.category as CategoryProduct;  
    ViewData["Title"] = Model.Title;    

    IQueryable<ProductModel> otherProducts = ViewBag.otherProducts as IQueryable<ProductModel>;
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~/">Home</a></li>
    @if  (category != null)
    {
        var li = category.ListParents();
        foreach (var l in li)
        {
            <li class="breadcrumb-item">
                <a asp-action="Index" asp-route-categoryslug="@l.Slug">@l.Title</a>
            </li>
        }
        <li class="breadcrumb-item">
                <a asp-action="Index" asp-route-categoryslug="@category.Slug">@category.Title</a>
        </li>
    } 
  </ol>
</nav>

<div class="detailpost">
    <h1>@Model.Title</h1>
    <div class="sapo">
        @Model.Description
    </div>
    <div>
        <p>
            Giá: <strong>@Model.Price</strong>
            <a asp-action="AddToCart" asp-route-productid="@Model.ProductID"  class="btn btn-danger">Đặt hàng</a>
        </p>
    </div>
    <div>
        <i>Cập nhật: @Model.DateUpdated</i> / 
        Tác giả: <strong>@Model.Author.UserName</strong>
    </div>

    @if (Model.Photos.Any())
    {
        <div class="d-flex flex-wrap">
            @foreach (var photo in Model.Photos)
            {
                <img class="w-50" src="/contents/Products/@photo.FileName" />
            }
        </div>
    }



    <hr>

    @Html.Raw(Model.Content)

</div>




@section Sidebar {
    @await Component.InvokeAsync("App.Components.CategoryProductSidebar", 
        new CategoryProductSidebar.CategorySidebarData()
        {
            Categories = categories,
            level = 0,
            categoryslug = category.Slug
        })

    <ul class="list-group">
    @foreach (var product in otherProducts)
    {
        <li class="list-group-item">
            <a asp-controller="ViewProduct" asp-action="Detail" asp-route-productslug="@product.Slug">
                @product.Title
            </a>
        </li>
    }
</ul>    
}

Areas/Product/Views/ViewProduct/Index.cshtml
@model List<ProductModel>

@using AppMvc.Components;
@{ 
    List<CategoryProduct> categories = ViewBag.categories as List<CategoryProduct>;
    CategoryProduct category = ViewBag.category as CategoryProduct;  
    ViewData["Title"] = (category != null) ? category.Title : 
                        "Tất cả sản phẩm";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~/">Home</a></li>
    @if  (category != null)
    {
        var li = category.ListParents();
        foreach (var l in li)
        {
            <li class="breadcrumb-item">
                <a asp-action="Index" asp-route-categoryslug="@l.Slug">@l.Title</a>
            </li>
        }
    } 
  </ol>
</nav>



<h1>@ViewData["Title"]</h1>
@if (category != null)
{
    <p>@category.Description</p>
}
else
{
    <p>Toàn bộ sản phẩm trong tất cả danh mục...</p>
}
<hr>
<div class="d-flex flex-wrap justify-content-between">
    @foreach (var product in Model)
    {
        var srcImg = "/contents/nophoto.png";
        if (product.Photos.Any())
        {
            srcImg = $"/contents/Products/{product.Photos.FirstOrDefault().FileName}";
        }

        <div class="card mb-2" style="width: 32%">
            <img src="@srcImg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">@product.Title</h5>
                <p class="card-text">
                    @product.Description
                </p>
                <p>
                    <strong class="text-danger">@product.ProductCategoryProducts.FirstOrDefault()?.Category.Title</strong>
                </p>
                <p>Giá: <strong>@product.Price</strong></p>
                
            </div>
            <div class="card-body">
                <a class="card-link" asp-controller="ViewProduct" asp-action="Detail" asp-route-productslug="@product.Slug">
                    Chi tiết
                </a>
                <a asp-action="AddToCart" asp-route-productid="@product.ProductID" class="btn btn-primary ml-4">Đặt hàng</a>
            </div>
        </div>
    }
</div>

@section Sidebar {
    @await Component.InvokeAsync("AppMvc.Components.CategoryProductSidebar", 
        new CategoryProductSidebar.CategorySidebarData()
        {
            Categories = categories,
            level = 0,  
            categoryslug = ViewBag.categoryslug
        })
}


<partial name="_PagingXTL" model="@ViewBag.pagingModel" />

Areas/Product/Views/ViewProduct/_LayoutProduct.cshtml
@{
    Layout = "_Layout";
}

<div class="row">
    <div class="col-md-3">
        @RenderSection("Sidebar", false)
    </div>

    <div class="col-md-9">
        @RenderBody()
    </div>

</div>